[buildPlans.iosevka-cosmic]
family = "Iosevka Cosmic"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = true

[buildPlans.iosevka-cosmic.variants.design]
capital-a = "curly-serifless"
capital-k = "curly-serifless"
capital-q = "curly-tailed"
capital-v = "curly"
capital-w = "curly"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
v = "curly"
w = "curly"
x = "curly-serifless"
y = "curly-turn"
long-s = "flat-hook-descending"
eszet = "traditional-descending"
turn-v = "curly"
lower-lambda = "straight-turn"
zero = "slashed"
one = "no-base"
two = "curly-neck"
three = "flat-top"
four = "semi-open"
five = "vertical-upper-left-bar"
six = "straight-bar"
seven = "curly-serifless"
eight = "two-circles"
nine = "straight-bar"
asterisk = "penta-low"
underscore = "high"
pilcrow = "low"
caret = "medium"
paren = "normal"
brace = "straight"
number-sign = "upright"
ampersand = "closed"
at = "threefold"
dollar = "through"
cent = "through"
percent = "rings-continuous-slash"
bar = "natural-slope"
lig-ltgteq = "flat"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "smooth"
punctuation-dot = "round"
diacritic-dot = "round"
lig-neq = "more-slanted"
lig-equal-chain = "without-notch"

  [buildPlans.iosevka-cosmic.ligations]
  inherits = "dlig"

[buildPlans.iosevka-cosmic.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.iosevka-cosmic.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-cosmic.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-cosmic.weights.heavy]
shape = 900
menu = 900
css = 900

[buildPlans.iosevka-cosmic-proportional]
family = "Iosevka MilkyWay"
spacing = "quasi-proportional"
serifs = "sans"
noCvSs = true
export-glyph-names = true

[buildPlans.iosevka-cosmic-proportional.variants.design]
capital-a = "curly-serifless"
capital-k = "curly-serifless"
capital-q = "curly-tailed"
capital-v = "curly"
capital-w = "curly"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
v = "curly"
w = "curly"
x = "curly-serifless"
y = "curly-turn"
long-s = "flat-hook-descending"
eszet = "traditional-descending"
turn-v = "curly"
lower-lambda = "straight-turn"
zero = "slashed"
one = "no-base"
two = "curly-neck"
three = "flat-top"
four = "semi-open"
five = "vertical-upper-left-bar"
six = "straight-bar"
seven = "curly-serifless"
eight = "two-circles"
nine = "straight-bar"
asterisk = "penta-low"
underscore = "high"
pilcrow = "low"
caret = "medium"
paren = "normal"
brace = "straight"
number-sign = "upright"
ampersand = "closed"
at = "threefold"
dollar = "through"
cent = "through"
percent = "rings-continuous-slash"
bar = "natural-slope"
lig-ltgteq = "flat"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "smooth"
punctuation-dot = "round"
diacritic-dot = "round"
lig-neq = "more-slanted"
lig-equal-chain = "without-notch"

[buildPlans.iosevka-cosmic-proportional.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.iosevka-cosmic-proportional.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-cosmic-proportional.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-cosmic-proportional.weights.heavy]
shape = 900
menu = 900
css = 900

[buildPlans.iosevka-cosmic-slab]
family = "Iosevka Andromeda"
spacing = "quasi-proportional"
serifs = "slab"
no-cv-ss = true
export-glyph-names = true

[buildPlans.iosevka-cosmic-slab.variants.design]
capital-a = "curly-serifless"
capital-k = "curly-serifless"
capital-q = "curly-tailed"
capital-v = "curly"
capital-w = "curly"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
v = "curly"
w = "curly"
x = "curly-serifless"
y = "curly-turn"
long-s = "flat-hook-descending"
eszet = "traditional-descending"
turn-v = "curly"
lower-lambda = "straight-turn"
zero = "slashed"
one = "no-base"
two = "curly-neck"
three = "flat-top"
four = "semi-open"
five = "vertical-upper-left-bar"
six = "straight-bar"
seven = "curly-serifless"
eight = "two-circles"
nine = "straight-bar"
asterisk = "penta-low"
underscore = "high"
pilcrow = "low"
caret = "medium"
paren = "normal"
brace = "straight"
number-sign = "upright"
ampersand = "closed"
at = "threefold"
dollar = "through"
cent = "through"
percent = "rings-continuous-slash"
bar = "natural-slope"
lig-ltgteq = "flat"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "smooth"
punctuation-dot = "round"
diacritic-dot = "round"
lig-neq = "more-slanted"
lig-equal-chain = "without-notch"

[buildPlans.iosevka-cosmic-slab.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.iosevka-cosmic-slab.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-cosmic-slab.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-cosmic-slab.weights.heavy]
shape = 900
menu = 900
css = 900

###################################################################################################
# Collect plans

[collectPlans.iosevka-cosmic]
from = [
    "iosevka-cosmic"
]

[collectPlans.iosevka-cosmic-proportional]
from = [
    "iosevka-cosmic-proportional"
]

[collectPlans.iosevka-cosmic-slab]
from = [
    "iosevka-cosmic-slab"
]
