[buildPlans.IosevkaCosmic]
family = "Iosevka Cosmic"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

[buildPlans.IosevkaCosmic.variants.design]
one = "no-base"
two = "curly-neck"
three = "flat-top"
four = "semi-open"
five = "vertical-upper-left-bar"
six = "straight-bar"
seven = "curly-serifless"
eight = "two-circles"
nine = "straight-bar"
zero = "slashed"
capital-a = "curly-serifless"
capital-k = "curly-serifless"
capital-q = "curly-tailed"
capital-v = "curly"
capital-w = "curly"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
v = "curly"
w = "curly"
x = "curly-serifless"
y = "curly-turn"
long-s = "flat-hook-descending"
eszet = "traditional-descending"
lower-lambda = "straight-turn"
diacritic-dot = "round"
punctuation-dot = "round"
asterisk = "penta-low"
underscore = "high"
caret = "medium"
ascii-grave = "straight"
ascii-single-quote = "straight"
paren = "normal"
brace = "straight"
number-sign = "upright"
ampersand = "closed"
at = "threefold"
dollar = "through"
cent = "through"
percent = "rings-continuous-slash"
bar = "natural-slope"
question = "smooth"
pilcrow = "low"
lig-ltgteq = "flat"
lig-neq = "more-slanted"
lig-equal-chain = "without-notch"

  [buildPlans.IosevkaCosmic.ligations]
  inherits = "dlig"

[buildPlans.IosevkaCosmic.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaCosmic.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCosmic.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaCosmic.weights.Heavy]
shape = 900
menu = 900
css = 900

[buildPlans.IosevkaMilkyWay]
family = "Iosevka MilkyWay"
spacing = "quasi-proportional"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

[buildPlans.IosevkaMilkyWay.variants.design]
one = "no-base"
two = "curly-neck"
three = "flat-top"
four = "semi-open"
five = "vertical-upper-left-bar"
six = "straight-bar"
seven = "curly-serifless"
eight = "two-circles"
nine = "straight-bar"
zero = "slashed"
capital-a = "curly-serifless"
capital-k = "curly-serifless"
capital-q = "curly-tailed"
capital-v = "curly"
capital-w = "curly"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
v = "curly"
w = "curly"
x = "curly-serifless"
y = "curly-turn"
long-s = "flat-hook-descending"
eszet = "traditional-descending"
lower-lambda = "straight-turn"
diacritic-dot = "round"
punctuation-dot = "round"
asterisk = "penta-low"
underscore = "high"
caret = "medium"
ascii-grave = "straight"
ascii-single-quote = "straight"
paren = "normal"
brace = "straight"
number-sign = "upright"
ampersand = "closed"
at = "threefold"
dollar = "through"
cent = "through"
percent = "rings-continuous-slash"
bar = "natural-slope"
question = "smooth"
pilcrow = "low"
lig-ltgteq = "flat"
lig-neq = "more-slanted"
lig-equal-chain = "without-notch"

[buildPlans.IosevkaMilkyWay.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaMilkyWay.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaMilkyWay.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaMilkyWay.weights.Heavy]
shape = 900
menu = 900
css = 900

[buildPlans.IosevkaAndromeda]
family = "Iosevka Andromeda"
spacing = "quasi-proportional"
serifs = "slab"
noCvSs = true
exportGlyphNames = true

[buildPlans.IosevkaAndromeda.variants.design]
one = "no-base"
two = "curly-neck"
three = "flat-top"
four = "semi-open"
five = "vertical-upper-left-bar"
six = "straight-bar"
seven = "curly-serifless"
eight = "two-circles"
nine = "straight-bar"
zero = "slashed"
capital-a = "curly-serifless"
capital-k = "curly-serifless"
capital-q = "curly-tailed"
capital-v = "curly"
capital-w = "curly"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
v = "curly"
w = "curly"
x = "curly-serifless"
y = "curly-turn"
long-s = "flat-hook-descending"
eszet = "traditional-descending"
lower-lambda = "straight-turn"
diacritic-dot = "round"
punctuation-dot = "round"
asterisk = "penta-low"
underscore = "high"
caret = "medium"
ascii-grave = "straight"
ascii-single-quote = "straight"
paren = "normal"
brace = "straight"
number-sign = "upright"
ampersand = "closed"
at = "threefold"
dollar = "through"
cent = "through"
percent = "rings-continuous-slash"
bar = "natural-slope"
question = "smooth"
pilcrow = "low"
lig-ltgteq = "flat"
lig-neq = "more-slanted"
lig-equal-chain = "without-notch"

[buildPlans.IosevkaAndromeda.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaAndromeda.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaAndromeda.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaAndromeda.weights.Heavy]
shape = 900
menu = 900
css = 900

###################################################################################################
# Collect plans

[collectPlans.IosevkaCosmic]
from = [
    "IosevkaCosmic", "IosevkaMilkyWay", "IosevkaAndromeda"
]
